### PR TITLE
change-image example

### PR DESCRIPTION
**Pull request by PaulHax**
Show how to set the image again.

Seems to work.  Does reset view after every `viewer.send({ type: 'setImage', image, name: 'image' });`

### CODE REVIEW

**Review by thewtex — APPROVED** [review]
@PaulHax nice!

Is it possible to remove the automatic camera reset?

**Comment by PaulHax** [comment]
I'll add an option: `skipCameraReset: false`

**Comment by PaulHax** [comment]
Added an event to view-3d to disable camera reset `  view3d?.getActor()?.send({ type: 'setAutoCameraReset', enableReset: false });`

**Review by thewtex — APPROVED** [review]
Awesome! :1st_place_medal:

**Pull request merged**
