### PR TITLE
WebRTC for agave-renderer

### PR DESCRIPTION
**Pull request by PaulHax**
Not sure WebRTC connection is kicking in yet...

### CODE REVIEW

**Comment by thewtex** [comment]
@oeway is this all we should need for WebRTC joy? :-D

**Comment by thewtex** [comment]
Is there a way to debug the WebRTC functionality? If it is working, should we see something in Chrome DevTools Networking, etc.?

**Comment by oeway** [comment]
Would this help? https://github.com/imjoy-team/imjoy-rpc/blob/master/imjoy-rpc-v2.md#peer-to-peer-connection-via-webrtc

We use it for control microscopes.

**Review by thewtex — APPROVED** [review]
@oeway thank you!!

This is awesome!

**Comment by oeway** [comment]
> Is there a way to debug the WebRTC functionality? If it is working, should we see something in Chrome DevTools Networking, etc.?

In Chrome, you can visit: chrome://webrtc-internals/ leave it open and if the webrtc is working you should see some event stream in that page.

BTW, I would like to try the agave renderer, how can I try it? Any docs for this?

**Comment by PaulHax** [comment]
No docs or all the code needed to spin up `agave-renderer` yet.

**Pull request merged**
