### PR TITLE
Add Vite

### LINKED ISSUE #8: Add vite/rollup configuration
- [ ] vite.config.js
- [ ] package.json scripts

### PR DESCRIPTION
**Pull request by PaulHax**
closes #8

Adds Lit too cuz I feel safer with a "framework" 😅

Did we want this at the root directory?

### CODE REVIEW

**Review by thewtex — APPROVED** [review]
:rocket: 

Thanks @PaulHax !

We can keep index.html at the top level for the demo app. Vite has its conventions (top level index.html) and going against them without dire need causes friction.

I see the convenience to Lit for quick template setup. It still irritates my anti-framework vibe :stuck_out_tongue_closed_eyes: :face_with_head_bandage: . Let's move forward with this for the app, but plan to update the ESM module output and package exports to only depend on xstate/itk-wasm. Lit metaphorically but not lit-erally :v: :guitar: :man_singer:

**Comment by thewtex** [comment]
> ESM module output and package exports to only depend on xstate/itk-wasm

Or, we have a `viewer` JS function element export *and* a Lit `viewerElement` export? @PaulHax what do you think?

**Comment by thewtex** [comment]
@PaulHax yes, you are right, it is looking like we will need different directories with their own package.json.

**Comment by thewtex** [comment]
> A "custom element" for the whole shebang could be neat.

Agreed. Very simple, quick usage in standard HTML.

> How should we separate the data xstate/itk-wasm and UI portions? Different directories with own package.json?

Yes, different directories with their own package.json.

We could manage the builds manually. I seen many similar projects also use [lerna](https://lerna.js.org/), but I have never used it. What do you think about it?

**Comment by PaulHax** [comment]
Yes lerna, but I think the package managers killed it with "workspaces" https://pnpm.io/workspaces

**Comment by thewtex** [comment]
Ah interesting, and https://pnpm.io/workspaces recommends [bit](https://github.com/teambit/bit). What do you think about bit?

**Comment by PaulHax** [comment]
From the linked article here was Bits's benefits for monorepo.

> you will never forget to change the type of your dependency
> you will never forget to add a package that you use to the dependencies of your project
> you will not publish your package with redundant dependencies
> you will get the same dependency versions in all your components (by default)
> you will do a lot less micromanagement of dependencies in your workspace

Suspect need to use the cloud service to feel the Bit value.  Feels like the Bit sweet spot is for medium sized companies.

**Comment by thewtex** [comment]
Hmm, they all seem like convenient niceties but not game changers. And not worth a dependency on a cloud service. Maybe we should try pnpm workspaces first.

**Pull request merged**
